from django.db import models
from django.contrib.auth.models import User


class Leads(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100, unique=True)
    message = models.CharField(max_length=500, blank=True)
    owner = models.ForeignKey(
        User, related_name="leads", on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

class Loans(models.Model):
    owner = models.ForeignKey(
        User, related_name="loan", on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    accountId = models.CharField(max_length=100)
    providerAccountId = models.CharField(max_length=100)
    accountName = models.CharField(max_length=100)
    accountStatus = models.CharField(max_length=100)
    accountNumber = models.CharField(max_length=100)
    aggregationSource = models.CharField(max_length=100)
    isAsset = models.CharField(max_length=100)
    balance_currency = models.CharField(max_length=100)
    balance_amount = models.CharField(max_length=100)
    includeInNetWorth = models.CharField(max_length=100)
    providerId = models.CharField(max_length=100)
    providerName = models.CharField(max_length=100)
    isManual = models.CharField(max_length=100)
    accountType = models.CharField(max_length=100)
    displayedName = models.CharField(max_length=100)
    createdDate = models.CharField(max_length=100)
    interestRateType = models.CharField(max_length=100)
    classification = models.CharField(max_length=100)
    lastUpdated = models.CharField(max_length=100)
    originalLoanAmount_currency = models.CharField(max_length=100)
    originalLoanAmount_amount = models.CharField(max_length=100)
    principalBalance_currency= models.CharField(max_length=100)
    principalBalance_amount = models.CharField(max_length=100)
    dataset_name = models.CharField(max_length=100)
    dataset_additionalStatus = models.CharField(max_length=100)
    dataset_updateEligibility = models.CharField(max_length=100)
    dataset_lastUpdated = models.CharField(max_length=100)
    dataset_lastUpdateAttempt = models.CharField(max_length=100)
    dataset_nextUpdateScheduled = models.CharField(max_length=100)

class Investments(models.Model):
    owner = models.ForeignKey(
        User, related_name="investment", on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True , null=True)
    accountId = models.CharField(max_length=100)
    providerAccountId = models.CharField(max_length=100)
    accountName = models.CharField(max_length=100)
    accountStatus = models.CharField(max_length=100)
    accountNumber = models.CharField(max_length=100)
    aggregationSource = models.CharField(max_length=100)
    isAsset = models.CharField(max_length=100)
    balance_currency = models.CharField(max_length=100)
    balance_amount = models.CharField(max_length=100)
    includeInNetWorth = models.CharField(max_length=100)
    providerId = models.CharField(max_length=100)
    providerName = models.CharField(max_length=100)
    isManual = models.CharField(max_length=100)
    accountType = models.CharField(max_length=100)
    displayedName = models.CharField(max_length=100)
    createdDate = models.CharField(max_length=100)
    cash_currency = models.CharField(max_length=100)
    cash_amount = models.CharField(max_length=100)
   
    lastUpdated = models.CharField(max_length=100)
    dataset_name = models.CharField(max_length=100)
    dataset_additionalStatus = models.CharField(max_length=100)
    dataset_updateEligibility = models.CharField(max_length=100)
    dataset_lastUpdated = models.CharField(max_length=100)
    dataset_lastUpdateAttempt = models.CharField(max_length=100)
    dataset_nextUpdateScheduled = models.CharField(max_length=100)

class CreditCard(models.Model):
    owner = models.ForeignKey(
        User, related_name="creditcard", on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    accountId = models.CharField(max_length=100)
    providerAccountId = models.CharField(max_length=100)
    accountName = models.CharField(max_length=100)
    accountStatus = models.CharField(max_length=100)
    accountNumber = models.CharField(max_length=100)
    aggregationSource = models.CharField(max_length=100)
    isAsset = models.CharField(max_length=100)
    balance_currency = models.CharField(max_length=100)
    balance_amount = models.CharField(max_length=100)
    includeInNetWorth = models.CharField(max_length=100)
    providerId = models.CharField(max_length=100)
    providerName = models.CharField(max_length=100)
    isManual = models.CharField(max_length=100)
    accountType = models.CharField(max_length=100)
    createdDate = models.CharField(max_length=100)
    cashApr = models.CharField(max_length=100)
    availableCreditCurrency = models.CharField(max_length=100)
    availableCreditAmount = models.CharField(max_length=100)
    lastUpdated = models.CharField(max_length=100)
    runningBalanceCurrency = models.CharField(max_length=100)
    runningBalanceamount = models.CharField(max_length=100)
    displayedName = models.CharField(max_length=100)
    dataset_name = models.CharField(max_length=100)
    dataset_additionalStatus = models.CharField(max_length=100)
    dataset_updateEligibility = models.CharField(max_length=100)
    dataset_lastUpdated = models.CharField(max_length=100)
    dataset_lastUpdateAttempt = models.CharField(max_length=100)
    dataset_nextUpdateScheduled = models.CharField(max_length=100)

class Banks(models.Model):
    owner = models.ForeignKey(
        User, related_name="banks", on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    accountId = models.CharField(max_length=200)
    providerAccountId = models.CharField(max_length=100)
    accountName = models.CharField(max_length=100)
    accountStatus = models.CharField(max_length=100)
    accountNumber = models.CharField(max_length=100)
    aggregationSource = models.CharField(max_length=100)
    isAsset = models.CharField(max_length=100)
    balance_currency = models.CharField(max_length=100)
    balance_amount = models.CharField(max_length=100)
    includeInNetWorth = models.CharField(max_length=100)
    providerId = models.CharField(max_length=100)
    providerName = models.CharField(max_length=100)
    isManual = models.CharField(max_length=100)
    accountType = models.CharField(max_length=100)
    createdDate = models.CharField(max_length=100)
    balance_current_currency = models.CharField(max_length=100)
    balance_current_amount = models.CharField(max_length=100)
    lastUpdated = models.CharField(max_length=100)
    displayedName = models.CharField(max_length=100)
    dataset_name = models.CharField(max_length=100)
    dataset_additionalStatus = models.CharField(max_length=100)
    dataset_updateEligibility = models.CharField(max_length=100)
    dataset_lastUpdated = models.CharField(max_length=100)
    dataset_lastUpdateAttempt = models.CharField(max_length=100)
    dataset_nextUpdateScheduled = models.CharField(max_length=100)